# Generated by Django 4.2 on 2023-06-03 16:11

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import place.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('type', models.CharField(choices=[('RECREATIONAL', 'RECREATIONAL'), ('SHOPPING', 'SHOPPING'), ('TOURISM', 'TOURISM')], default='NOTSET', max_length=13)),
                ('admin_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourismPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('image', models.ImageField(upload_to=place.models.places_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.places')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('image', models.ImageField(upload_to=place.models.places_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.places')),
            ],
        ),
        migrations.CreateModel(
            name='RecreationalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('image', models.ImageField(upload_to=place.models.places_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.places')),
            ],
        ),
    ]
