# Generated by Django 4.2 on 2023-06-03 13:24

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered                 in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_info', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, default='default.jpeg', upload_to=core.models.user_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('first_time_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('detail', models.TextField(blank=True, max_length=220, null=True)),
                ('type', models.CharField(choices=[('HOTEL_AND_RESIDENCE', 'HOTEL_AND_RESIDENCE'), ('TRAVEL_AGENCY', 'TRAVEL_AGENCY'), ('TOURIST_TOUR', 'TOURIST_TOUR')], default='NOTSET', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered                 in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('type_of_transportation', models.CharField(choices=[('bus', 'BUS'), ('train', 'TRAIN'), ('airplane', 'AIRPLANE'), ('ship', 'SHIP'), ('notset', 'NOTSET')], db_index=True, default='notset', max_length=11)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='TouristTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('facilities', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('type_of_transportation', models.CharField(choices=[('boat', 'BOAT'), ('car', 'CAR'), ('motorcycle', 'MOTORCYCLE')], db_index=True, default='car', max_length=11)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAndResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_hotel', models.CharField(choices=[('HOTEL', 'HOTEL'), ('RESIDENCE', 'RESIDENCE'), ('NOTSET', 'NOTSET')], db_index=True, default='NOTSET', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('facilities', models.TextField(max_length=500)),
                ('star', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost per night')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
