# Generated by Django 4.2 on 2023-05-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_updated_at_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(max_length=12),
        ),
    ]
